function [layers,options] = srcnn_model(input_size,batchSize,valData,valLabels,valFrequency)
layers = [ ...
        imageInputLayer(input_size,'Normalization','none')
        convolution2dLayer(9,64,'Padding','same')
        reluLayer
        convolution2dLayer(1,32,'Padding','same')
        reluLayer
        convolution2dLayer(5,1,'Padding','same')
        regressionLayer
    ];

    % Set up a training policy
options = trainingOptions('adam', ...
    'ExecutionEnvironment','multi-gpu',...
    'InitialLearnRate',0.01, ...
    'MaxEpochs',100, ...
    'Shuffle','every-epoch', ...
    'Verbose',false, ...
    'Plots','training-progress', ...
    'MiniBatchSize',batchSize, ...
    'ValidationData',{valData, valLabels}, ...
    'ValidationFrequency',valFrequency, ...
    'ValidationPatience',5);
end